[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = ["forge-std/=lib/forge-std/src/"]

[profile.ci]
fuzz = { runs = 10000 }

[rpc_endpoints]
anvil = "http://localhost:8545"
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
